services:
  - type: web
    name: santeko-api
    env: docker
    plan: free

    envVars:
      - key: PORT
        value: 10000

    headers:
      # Désactive TOTALEMENT gzip et brotli
      - path: /*
        name: Content-Encoding
        value: ""
      - path: /*
        name: Accept-Encoding
        value: ""
